# Generated by Django 4.2.5 on 2023-10-22 08:44

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ('catalog', '0001_initial'),
        ('catalog', '0002_rename_catalogitems_item'),
        ('catalog', '0003_alter_item_table'),
        ('catalog', '0004_item_is_published_item_name_alter_item_id_and_more'),
        ('catalog', '0005_alter_item_name'),
        ('catalog', '0006_category_tag'),
        ('catalog', '0007_item_category_item_tags'),
        ('catalog', '0008_alter_category_options_alter_item_options_and_more'),
        ('catalog', '0009_alter_category_options_alter_item_options_and_more'),
        ('catalog', '0010_alter_category_weight'),
        ('catalog', '0011_alter_category_slug_alter_tag_slug'),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='item',
            table='catalog_item',
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='Опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='id',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                validators=[catalog.models.perfect_validator],
                verbose_name='Текст',
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Опубликован ли товар?',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название товара',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите слаг',
                        max_length=200,
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        help_text='Введите вес',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'db_table': 'catalog_category',
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Опубликован ли товар?',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название товара',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите слаг',
                        max_length=200,
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'db_table': 'catalog_tag',
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='id',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Опубликован ли товар?',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Введите название товара',
                max_length=150,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='Выберите теги.',
                to='catalog.tag',
                verbose_name='Теги',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Введите текст',
                validators=[catalog.models.perfect_validator],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Опубликован ли товар?',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Введите название товара',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='Выберите теги.',
                to='catalog.tag',
                verbose_name='теги',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Введите текст',
                validators=[catalog.models.perfect_validator],
                verbose_name='текст',
            ),
        ),
    ]
